disable_3d = "yes"
module_text_server_adv_enabled = "no"
module_text_server_fb_enabled = "yes"
disable_advanced_gui = "yes"
deprecated = "no"  # Disables deprecated features
module_openxr_enabled = "no"  # Disables Virtual Reality/Augmented Reality stuff
minizip = "no"  # Disables ZIP archive support
modules_enabled_by_default = "no"
module_gdscript_enabled = "yes"
module_text_server_fb_enabled = "yes"
module_freetype_enabled = "yes"
module_svg_enabled = "yes"
module_webp_enabled = "yes"
module_godot_physics_2d_enabled = "yes"
